### ISSUE TITLE
Don't write to the artifacts directory

### ISSUE THREAD

**Issue by maleadt** [JuliaAI/OpenML.jl#20]
The code here writes to `.julia/artifacts`: https://github.com/JuliaAI/OpenML.jl/blob/738790c086c11808b90911cfe2df169f3d4c8ddf/src/data.jl#L71-L72

That directory really isn't intended to be written like that, and should only contain content-addressable artifacts. It would be better to use Scratch.jl, https://github.com/JuliaPackaging/Scratch.jl, and write the data to a scratch directory.

**Comment by ablaom** [comment]
@maleadt Thanks for chiming in here. I didn't know about Scratch.jl. 

In this case the use case is "download once read many times", which I would have thought made Artifiacts the proper choice here. What makes you say otherwise? Is there something not kosher about the implementation. Not sure I understand what you mean by "content-addressable" here. 

@jbrea may also want to comment.

**Comment by maleadt** [comment]
> In this case the use case is "download once read many times", which I would have thought made Artifiacts the proper choice here.

It is, but not how you're using it. You're creating an `OpenMLArtifacts.toml` in `~/.julia/artifacts`, while an `Artifacts.toml` should ideally be a committed, static file in the OpenML.jl repository. The `bind_artifact!` functionality is intended to be executed by package developers when creating such a static `Artifacts.toml`, and not dynamically at run time.

If for some reason you _need_ to dynamically generate this file, it still shouldn't reside in `~/.julia/artifacts`, but in a scratchspace (i.e., the downloaded artifacts themselves will still be managed by Julia and downloaded into `~/.julia/artifacts`, but your package shouldn't touch that directory directly). Hope that helps.
